language: elixir
sudo: false
env:
  - MIX_ENV=test
elixir:
  - 1.8
otp_release:
  - 22.0
script: mix coveralls.travis
cache:
  directories:
    - ~/.mix
    - ~/.hex
jobs:
  include:
    - stage: format
      env:
        - MIX_ENV=dev
      script: mix format --check-formatted
      elixir: 1.8
    - stage: credo
      env:
        - MIX_ENV=dev
      script: mix credo --strict
      elixir: 1.8
    - stage: dialyzer
      env:
        - MIX_ENV=dev
      before_script: travis_wait mix dialyzer --plt
      script: mix dialyzer --halt-exit-status
      elixir: 1.8
