on:
  workflow_call:
    inputs:
      plugin:
        type: string
        required: true
      constraint:
        type: string
        default: ""
        required: false

name: "ASDF Update"

jobs:
  asdf_update:
    name: "${{ inputs.plugin }}"

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - name: ASDF Install
        uses: asdf-vm/actions/install@v1
      - name: "Get Newest Version"
        id: newestVersion
        run: |
          LATEST_VERSION=$(asdf latest "${{ inputs.plugin }}" "${{ inputs.constraint }}")
          echo "Latest (${{ inputs.constraint }}): $LATEST_VERSION"
          echo ::set-output name=LATEST_VERSION::${LATEST_VERSION}
      - name: "Try Installing new version"
        run: |
          asdf install "${{ inputs.plugin }}" "${{ steps.newestVersion.outputs.LATEST_VERSION }}"
      - name: "Apply latest version to .tool-versions"
        run: |
          asdf local "${{ inputs.plugin }}" "${{ steps.newestVersion.outputs.LATEST_VERSION }}"
      - uses: peter-evans/create-pull-request@v4
        with:
          add-paths: '.tool-versions'
          commit-message: 'Update ${{ inputs.plugin }} to ${{ steps.newestVersion.outputs.LATEST_VERSION }}'
          title: 'Update ${{ inputs.plugin }} to ${{ steps.newestVersion.outputs.LATEST_VERSION }}'
          branch: 'asdf/${{ inputs.plugin }}/${{ steps.newestVersion.outputs.LATEST_VERSION }}'
          delete-branch: true
          labels: 'asdf,enhancement'
